# Generated by Django 4.2.20 on 2025-04-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='region',
            managers=[
            ],
        ),
    ]
